import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

export type AppLanguage = 'ru' | 'kk' | 'en';

const translations = {
  ru: {
    home: 'Главная',
    library: 'Библиотека',
    official: 'Онлайн',
    add: 'Добавить',
    admin: 'Админ',
    profile: 'Профиль',
    settings: 'Справочники',
    gutendex: 'Мировая база',
    language: 'Язык интерфейса',
    users: 'Пользователи',
    books: 'Книги',
    save: 'Сохранить',
    delete: 'Удалить',
    role: 'Роль',
    reader: 'Чтение',
    login_title: 'PocketLib',
    college_name: 'Polytech College Almaty',
    login_subtitle: 'Библиотека учебных материалов колледжа',
    password: 'Пароль',
    sign_in: 'Войти',
    no_account_register: 'Нет аккаунта? Зарегистрироваться',
    register: 'Регистрация',
    full_name: 'ФИО',
    already_have_account: 'Уже есть аккаунт? Войти',
    group: 'Группа',
    choose_group: 'Выберите свою учебную группу',
    groups_not_created: 'Группы пока не созданы администратором',
    choose_group_title: 'Выберите группу',
    close: 'Закрыть',
    logout: 'Выйти из аккаунта',
    welcome_back: 'С возвращением,',
    student: 'Студент',
    teacher: 'Преподаватель',
    materials: 'Материалов',
    offline: 'Офлайн',
    disciplines: 'Дисциплин',
    latest_added: 'Последние добавленные',
    all: 'Все',
    no_materials: 'Пока нет учебных материалов',
    for_your_group: 'Для вашей группы',
    no_group_materials: 'Для вашей группы пока нет материалов',
    choose_group_hint: 'Выберите группу при регистрации',
    add_material: 'Добавить учебный материал',
    title_required: 'Название *',
    author_teacher: 'Автор / преподаватель',
    description: 'Описание',
    material_type: 'Тип материала',
    textbook: 'Учебник',
    lecture: 'Лекция',
    manual: 'Методичка',
    practice: 'Практика',
    language_short: 'Язык',
    semester: 'Семестр',
    discipline: 'Дисциплина',
    choose_discipline: 'Выберите дисциплину',
    course: 'Курс',
    choose_course: 'Выберите курс для рекомендаций',
    choose_discipline_first: 'Сначала выберите дисциплину',
    category: 'Категория',
    choose_category: 'Выберите категорию',
    choose_file: 'Выбрать файл (PDF, TXT, EPUB)',
    unsupported_format: 'Неподдерживаемый формат',
    choose_supported_file: 'Выберите PDF, TXT или EPUB файл.',
    error: 'Ошибка',
    success: 'Успех',
    fill_title_file: 'Введите название и выберите файл',
    fill_all_fields: 'Пожалуйста, заполните все поля',
    invalid_login: 'Неверный email или пароль',
    backend_server: 'Сервер backend',
    backend_url: 'Адрес backend',
    backend_url_hint: 'Для APK на телефоне укажите адрес, доступный с телефона, например http://192.168.1.10:8080. localhost и 10.0.2.2 на реальном телефоне не подходят.',
    invalid_server_url: 'Укажите корректный адрес сервера, например http://192.168.1.10:8080',
    test_connection: 'Проверить соединение',
    server_connection_ok: 'Соединение с backend работает',
    server_connection_failed: 'Backend недоступен с этого устройства',
    server_saved: 'Адрес backend сохранен',
    saved_material: 'Материал успешно добавлен в библиотеку',
    save_failed: 'Не удалось сохранить материал',
    no_add_rights: 'У вас нет прав для добавления материалов.',
    read_in_app: 'Читать в приложении',
    open_document: 'Открыть документ',
    open_source: 'Открыть официальный источник',
    online: 'Онлайн',
    download_for_reading: 'Скачать для чтения',
    unknown_author: 'Автор неизвестен',
    on_server: 'На сервере',
    read_pages_prefix: 'Прочитано: стр.',
    of: 'из',
    assigned_discipline: 'Назначена дисциплина',
    delete_book_title: 'Удалить книгу?',
    delete_book_message: 'будет удалена из библиотеки.',
    cancel: 'Отмена',
    download_first: 'Сначала скачайте книгу на устройство',
    no_available_file: 'Для этой книги пока нет доступного файла или ссылки',
    missing_server_file: 'Файл книги пока не загружен на сервер',
    file_ready: 'Книга скачана и готова к чтению',
    download_failed: 'Не удалось скачать книгу',
    source: 'Источник',
    not_specified: 'не указано',
    available_in_app: 'Доступно чтение внутри приложения',
    downloaded_document: 'Документ скачан на устройство',
    server_file_hint: 'Файл хранится на сервере, скачайте его для чтения',
    external_link_available: 'Доступна внешняя ссылка',
    description_missing: 'Описание отсутствует.',
    download_book: 'Скачать книгу',
    access_restricted: 'Доступ ограничен',
    read: 'Читать',
    no_file: 'Нет файла',
    assign_discipline: 'Назначить дисциплину',
    search_materials: 'Поиск материалов...',
    offline_only: 'Только офлайн',
    available_online: 'Доступно онлайн',
    favorite_books: 'Избранное',
    continue_reading: 'Продолжить чтение',
    materials_not_found: 'Материалы не найдены',
    reset_filters: 'Сбросить фильтры',
    filters: 'Фильтры',
    sort: 'Сортировка',
    sort_newest: 'Сначала новые',
    sort_title: 'По названию',
    sort_author: 'По автору',
    sort_offline: 'Офлайн сверху',
    all_disciplines: 'Все дисциплины',
    all_categories: 'Все категории',
    material_types: 'Тип материала',
    all_types: 'Все типы',
    reset: 'Сбросить',
    apply: 'Применить',
    empty_catalog: 'Справочник пуст',
    no_courses_for_discipline: 'Для дисциплины пока нет курсов',
    catalog_access_denied: 'Справочники доступны администратору и преподавателю.',
    catalog_subtitle: 'Дисциплины, курсы и учебные группы',
    new_discipline: 'Новая дисциплина',
    discipline_name: 'Название дисциплины',
    code_optional: 'Код (необязательно)',
    name_kk: 'Название на казахском',
    name_en: 'Название на английском',
    add_course: 'Добавить курс',
    course_name: 'Название курса',
    course_year_1_6: 'Номер курса (1-6)',
    new_group: 'Новая группа',
    group_name: 'Название группы',
    group_course: 'Курс группы',
    admission_year: 'Год поступления',
    discipline_not_specified: 'Дисциплина не указана',
    create_discipline_course_first: 'Сначала создайте дисциплину и курс.',
    add_discipline: 'Добавить дисциплину',
    create_first_discipline: 'Создайте первую дисциплину, затем добавьте к ней курсы.',
    add_group: 'Добавить группу',
    groups_empty: 'Группы пока не созданы. Студенты смогут выбрать группу после ее добавления.',
    course_year_invalid: 'Курс должен быть от 1 до 6',
    group_required: 'Укажите название группы и курс',
    group_add_failed: 'Не удалось добавить группу. Возможно, такое название уже есть.',
    discipline_added: 'Дисциплина добавлена',
    course_added: 'Курс добавлен',
    group_added: 'Группа добавлена',
    admin_access_denied: 'Доступ разрешен только администратору.',
    admin_panel: 'Панель администратора',
    admin_subtitle: 'Пользователи и каталог PocketLib',
    add_book: 'Добавить книгу',
    group_label: 'Группа',
    primary_admin: 'Основной админ',
    role_updated: 'Роль пользователя обновлена',
    delete_user_title: 'Удалить пользователя?',
    specialty: 'Специальность',
    information_systems: 'Информационные системы',
    registration_date: 'Дата регистрации',
    notifications: 'Уведомления',
    appearance: 'Оформление',
    light_theme: 'Светлая тема',
    dark_theme: 'Темная тема',
    year: 'Год',
    read_online: 'Читать онлайн',
    book_search: 'Поиск книг',
    search_books_placeholder: 'Название, автор или тема...',
    search_button: 'Найти',
    enter_query_hint: 'Введите запрос и нажмите «Найти»',
    nothing_found: 'Ничего не найдено',
    added_to_library: 'добавлена в библиотеку',
    add_book_error: 'Ошибка при добавлении книги',
    open_literature: 'Открытая литература',
    gutenberg_search_subtitle: 'Поиск по базе Project Gutenberg (классика)',
    gutenberg_placeholder: 'Название или автор (на англ.)...',
    find_classics_hint: 'Найдите мировую классику для своей коллекции',
    reader_loading: 'Загрузка книги...',
    epub_text_failed: 'EPUB не удалось преобразовать в текст',
    file_original_hint: 'Файл лучше открыть как оригинальный документ',
    download_from_card: 'Сначала скачайте книгу из карточки материала.',
    prepare_epub_text: 'Подготавливаю текстовую версию EPUB...',
    epub_text_open_failed: 'Не удалось открыть текстовую версию EPUB',
    open_original_failed: 'Не удалось открыть оригинальный документ. Проверьте, установлен ли просмотрщик PDF/EPUB.',
    bookmark_added_section: 'Закладка добавлена: раздел',
    bookmark_added_page: 'Закладка добавлена: стр.',
    bookmark_removed: 'Закладка удалена',
    section: 'Раздел',
    page: 'Страница',
    original_document: 'Оригинальный документ',
    bookmarks: 'Закладки',
    no_bookmarks: 'Закладок пока нет',
    document: 'Документ',
    pdf_original_hint: 'PDF открывается как оригинальный файл, поэтому сохраняются изображения, выделения, таблицы и верстка страницы.',
    original_format_hint: 'Этот формат лучше читать как оригинальный документ, чтобы не потерять медиа и оформление.',
    reader_settings: 'Настройки чтения',
    text_size: 'Размер текста',
    font: 'Шрифт',
    theme: 'Тема',
    line_spacing: 'Интервал',
    page_width: 'Ширина страницы',
    theme_paper: 'Бумага',
    theme_white: 'Светлая',
    theme_green: 'Спокойная',
    theme_dark: 'Темная',
    font_serif: 'Книжный',
    font_sans: 'Современный',
    font_mono: 'Моно',
    font_system: 'Системный',
    width_narrow: 'Узко',
    width_medium: 'Средне',
    width_wide: 'Широко',
    line_compact: 'Плотно',
    line_normal: 'Обычно',
    line_relaxed: 'Свободно',
    preview_text: 'Так будет выглядеть страница книги.',
    text_mode: 'Текстовый режим',
    done: 'Готово',
  },
  kk: {
    home: 'Басты бет',
    library: 'Кітапхана',
    official: 'Онлайн',
    add: 'Қосу',
    admin: 'Әкімші',
    profile: 'Профиль',
    settings: 'Анықтамалықтар',
    gutendex: 'Әлемдік база',
    language: 'Интерфейс тілі',
    users: 'Пайдаланушылар',
    books: 'Кітаптар',
    save: 'Сақтау',
    delete: 'Жою',
    role: 'Рөл',
    reader: 'Оқу',
    login_title: 'PocketLib',
    college_name: 'Polytech College Almaty',
    login_subtitle: 'Колледждің оқу материалдары кітапханасы',
    password: 'Құпия сөз',
    sign_in: 'Кіру',
    no_account_register: 'Аккаунт жоқ па? Тіркелу',
    register: 'Тіркелу',
    full_name: 'Аты-жөні',
    already_have_account: 'Аккаунтыңыз бар ма? Кіру',
    group: 'Топ',
    choose_group: 'Оқу тобыңызды таңдаңыз',
    groups_not_created: 'Топтарды әкімші әлі құрған жоқ',
    choose_group_title: 'Топты таңдаңыз',
    close: 'Жабу',
    logout: 'Аккаунттан шығу',
    welcome_back: 'Қайта қош келдіңіз,',
    student: 'Студент',
    teacher: 'Оқытушы',
    materials: 'Материал',
    offline: 'Офлайн',
    disciplines: 'Пән',
    latest_added: 'Соңғы қосылғандар',
    all: 'Барлығы',
    no_materials: 'Оқу материалдары әлі жоқ',
    for_your_group: 'Сіздің тобыңызға',
    no_group_materials: 'Сіздің тобыңызға материалдар әлі жоқ',
    choose_group_hint: 'Тіркелу кезінде топты таңдаңыз',
    add_material: 'Оқу материалын қосу',
    title_required: 'Атауы *',
    author_teacher: 'Автор / оқытушы',
    description: 'Сипаттама',
    material_type: 'Материал түрі',
    textbook: 'Оқулық',
    lecture: 'Дәріс',
    manual: 'Әдістеме',
    practice: 'Практика',
    language_short: 'Тіл',
    semester: 'Семестр',
    discipline: 'Пән',
    choose_discipline: 'Пәнді таңдаңыз',
    course: 'Курс',
    choose_course: 'Ұсыным үшін курсты таңдаңыз',
    choose_discipline_first: 'Алдымен пәнді таңдаңыз',
    category: 'Санат',
    choose_category: 'Санатты таңдаңыз',
    choose_file: 'Файл таңдау (PDF, TXT, EPUB)',
    unsupported_format: 'Қолдау көрсетілмейтін формат',
    choose_supported_file: 'PDF, TXT немесе EPUB файлын таңдаңыз.',
    error: 'Қате',
    success: 'Сәтті',
    fill_title_file: 'Атауын енгізіп, файлды таңдаңыз',
    fill_all_fields: 'Барлық өрістерді толтырыңыз',
    invalid_login: 'Email немесе құпия сөз қате',
    backend_server: 'Backend сервері',
    backend_url: 'Backend мекенжайы',
    backend_url_hint: 'Телефондағы APK үшін телефоннан қолжетімді мекенжайды көрсетіңіз, мысалы http://192.168.1.10:8080. Нақты телефонда localhost және 10.0.2.2 жарамайды.',
    invalid_server_url: 'Сервер мекенжайын дұрыс көрсетіңіз, мысалы http://192.168.1.10:8080',
    test_connection: 'Қосылымды тексеру',
    server_connection_ok: 'Backend қосылымы жұмыс істейді',
    server_connection_failed: 'Бұл құрылғыдан backend қолжетімсіз',
    server_saved: 'Backend мекенжайы сақталды',
    saved_material: 'Материал кітапханаға сәтті қосылды',
    save_failed: 'Материалды сақтау мүмкін болмады',
    no_add_rights: 'Материал қосуға құқығыңыз жоқ.',
    read_in_app: 'Қолданбада оқу',
    open_document: 'Құжатты ашу',
    open_source: 'Ресми дереккөзді ашу',
    online: 'Онлайн',
    download_for_reading: 'Оқу үшін жүктеу',
    unknown_author: 'Авторы белгісіз',
    on_server: 'Серверде',
    read_pages_prefix: 'Оқылды: бет',
    of: 'ішінен',
    assigned_discipline: 'Пән тағайындалды',
    delete_book_title: 'Кітапты жою керек пе?',
    delete_book_message: 'кітапханадан жойылады.',
    cancel: 'Болдырмау',
    download_first: 'Алдымен кітапты құрылғыға жүктеңіз',
    no_available_file: 'Бұл кітап үшін файл немесе сілтеме әлі жоқ',
    missing_server_file: 'Кітап файлы серверге әлі жүктелмеген',
    file_ready: 'Кітап жүктелді және оқуға дайын',
    download_failed: 'Кітапты жүктеу мүмкін болмады',
    source: 'Дереккөз',
    not_specified: 'көрсетілмеген',
    available_in_app: 'Қолданба ішінде оқуға болады',
    downloaded_document: 'Құжат құрылғыға жүктелді',
    server_file_hint: 'Файл серверде сақталған, оқу үшін жүктеңіз',
    external_link_available: 'Сыртқы сілтеме қолжетімді',
    description_missing: 'Сипаттама жоқ.',
    download_book: 'Кітапты жүктеу',
    access_restricted: 'Қолжетімділік шектелген',
    read: 'Оқу',
    no_file: 'Файл жоқ',
    assign_discipline: 'Пән тағайындау',
    search_materials: 'Материалдарды іздеу...',
    offline_only: 'Тек офлайн',
    available_online: 'Онлайн қолжетімді',
    favorite_books: 'Таңдаулылар',
    continue_reading: 'Оқуды жалғастыру',
    materials_not_found: 'Материалдар табылмады',
    reset_filters: 'Сүзгілерді тазарту',
    filters: 'Сүзгілер',
    sort: 'Сұрыптау',
    sort_newest: 'Алдымен жаңалары',
    sort_title: 'Атауы бойынша',
    sort_author: 'Авторы бойынша',
    sort_offline: 'Офлайн жоғарыда',
    all_disciplines: 'Барлық пәндер',
    all_categories: 'Барлық санаттар',
    material_types: 'Материал түрі',
    all_types: 'Барлық түрлер',
    reset: 'Тазарту',
    apply: 'Қолдану',
    empty_catalog: 'Анықтамалық бос',
    no_courses_for_discipline: 'Бұл пәнде әзірге курстар жоқ',
    catalog_access_denied: 'Анықтамалықтар әкімші мен оқытушыға қолжетімді.',
    catalog_subtitle: 'Пәндер, курстар және оқу топтары',
    new_discipline: 'Жаңа пән',
    discipline_name: 'Пән атауы',
    code_optional: 'Код (міндетті емес)',
    name_kk: 'Қазақша атауы',
    name_en: 'Ағылшынша атауы',
    add_course: 'Курс қосу',
    course_name: 'Курс атауы',
    course_year_1_6: 'Курс нөмірі (1-6)',
    new_group: 'Жаңа топ',
    group_name: 'Топ атауы',
    group_course: 'Топ курсы',
    admission_year: 'Қабылдау жылы',
    discipline_not_specified: 'Пән көрсетілмеген',
    create_discipline_course_first: 'Алдымен пән мен курс жасаңыз.',
    add_discipline: 'Пән қосу',
    create_first_discipline: 'Алдымен бірінші пәнді жасап, оған курстар қосыңыз.',
    add_group: 'Топ қосу',
    groups_empty: 'Топтар әлі жасалмаған. Студенттер топ қосылғаннан кейін таңдай алады.',
    course_year_invalid: 'Курс 1-ден 6-ға дейін болуы керек',
    group_required: 'Топ атауы мен курсты көрсетіңіз',
    group_add_failed: 'Топты қосу мүмкін болмады. Мұндай атау бұрыннан бар болуы мүмкін.',
    discipline_added: 'Пән қосылды',
    course_added: 'Курс қосылды',
    group_added: 'Топ қосылды',
    admin_access_denied: 'Қолжетімділік тек әкімшіге рұқсат етілген.',
    admin_panel: 'Әкімші панелі',
    admin_subtitle: 'PocketLib пайдаланушылары мен каталогы',
    add_book: 'Кітап қосу',
    group_label: 'Топ',
    primary_admin: 'Негізгі әкімші',
    role_updated: 'Пайдаланушы рөлі жаңартылды',
    delete_user_title: 'Пайдаланушыны жою керек пе?',
    specialty: 'Мамандық',
    information_systems: 'Ақпараттық жүйелер',
    registration_date: 'Тіркелген күні',
    notifications: 'Хабарландырулар',
    appearance: 'Безендіру',
    light_theme: 'Жарық тақырып',
    dark_theme: 'Қараңғы тақырып',
    year: 'Жыл',
    read_online: 'Онлайн оқу',
    book_search: 'Кітап іздеу',
    search_books_placeholder: 'Атауы, авторы немесе тақырыбы...',
    search_button: 'Іздеу',
    enter_query_hint: 'Сұранысты енгізіп, «Іздеу» түймесін басыңыз',
    nothing_found: 'Ештеңе табылмады',
    added_to_library: 'кітапханаға қосылды',
    add_book_error: 'Кітапты қосу кезінде қате шықты',
    open_literature: 'Ашық әдебиет',
    gutenberg_search_subtitle: 'Project Gutenberg базасынан іздеу (классика)',
    gutenberg_placeholder: 'Атауы немесе авторы (ағылш.)...',
    find_classics_hint: 'Жинағыңызға әлемдік классиканы табыңыз',
    reader_loading: 'Кітап жүктелуде...',
    epub_text_failed: 'EPUB мәтінге түрленбеді',
    file_original_hint: 'Файлды бастапқы құжат ретінде ашқан дұрыс',
    download_from_card: 'Алдымен кітапты материал карточкасынан жүктеңіз.',
    prepare_epub_text: 'EPUB мәтіндік нұсқасы дайындалуда...',
    epub_text_open_failed: 'EPUB мәтіндік нұсқасын ашу мүмкін болмады',
    open_original_failed: 'Бастапқы құжатты ашу мүмкін болмады. PDF/EPUB қарау қолданбасы орнатылғанын тексеріңіз.',
    bookmark_added_section: 'Бетбелгі қосылды: бөлім',
    bookmark_added_page: 'Бетбелгі қосылды: бет',
    bookmark_removed: 'Бетбелгі жойылды',
    section: 'Бөлім',
    page: 'Бет',
    original_document: 'Бастапқы құжат',
    bookmarks: 'Бетбелгілер',
    no_bookmarks: 'Бетбелгілер әлі жоқ',
    document: 'Құжат',
    pdf_original_hint: 'PDF бастапқы файл ретінде ашылады, сондықтан суреттер, кестелер және бет пішімі сақталады.',
    original_format_hint: 'Медиа мен безендіруді жоғалтпау үшін бұл форматты бастапқы құжат ретінде оқыған дұрыс.',
    reader_settings: 'Оқу баптаулары',
    text_size: 'Мәтін өлшемі',
    font: 'Қаріп',
    theme: 'Тақырып',
    line_spacing: 'Жол аралығы',
    page_width: 'Бет ені',
    theme_paper: 'Қағаз',
    theme_white: 'Жарық',
    theme_green: 'Жайлы',
    theme_dark: 'Қараңғы',
    font_serif: 'Кітаптық',
    font_sans: 'Заманауи',
    font_mono: 'Моно',
    font_system: 'Жүйелік',
    width_narrow: 'Тар',
    width_medium: 'Орташа',
    width_wide: 'Кең',
    line_compact: 'Тығыз',
    line_normal: 'Қалыпты',
    line_relaxed: 'Кең',
    preview_text: 'Кітап беті осылай көрінеді.',
    text_mode: 'Мәтіндік режим',
    done: 'Дайын',
  },
  en: {
    home: 'Home',
    library: 'Library',
    official: 'Online',
    add: 'Add',
    admin: 'Admin',
    profile: 'Profile',
    settings: 'Catalogs',
    gutendex: 'World library',
    language: 'Interface language',
    users: 'Users',
    books: 'Books',
    save: 'Save',
    delete: 'Delete',
    role: 'Role',
    reader: 'Reader',
    login_title: 'PocketLib',
    college_name: 'Polytech College Almaty',
    login_subtitle: 'College learning materials library',
    password: 'Password',
    sign_in: 'Sign in',
    no_account_register: 'No account? Register',
    register: 'Registration',
    full_name: 'Full name',
    already_have_account: 'Already have an account? Sign in',
    group: 'Group',
    choose_group: 'Choose your study group',
    groups_not_created: 'Groups have not been created by the administrator yet',
    choose_group_title: 'Choose a group',
    close: 'Close',
    logout: 'Sign out',
    welcome_back: 'Welcome back,',
    student: 'Student',
    teacher: 'Teacher',
    materials: 'Materials',
    offline: 'Offline',
    disciplines: 'Disciplines',
    latest_added: 'Recently added',
    all: 'All',
    no_materials: 'No learning materials yet',
    for_your_group: 'For your group',
    no_group_materials: 'No materials for your group yet',
    choose_group_hint: 'Choose a group during registration',
    add_material: 'Add learning material',
    title_required: 'Title *',
    author_teacher: 'Author / teacher',
    description: 'Description',
    material_type: 'Material type',
    textbook: 'Textbook',
    lecture: 'Lecture',
    manual: 'Manual',
    practice: 'Practice',
    language_short: 'Language',
    semester: 'Semester',
    discipline: 'Discipline',
    choose_discipline: 'Choose a discipline',
    course: 'Course',
    choose_course: 'Choose a course for recommendations',
    choose_discipline_first: 'Choose a discipline first',
    category: 'Category',
    choose_category: 'Choose a category',
    choose_file: 'Choose file (PDF, TXT, EPUB)',
    unsupported_format: 'Unsupported format',
    choose_supported_file: 'Choose a PDF, TXT or EPUB file.',
    error: 'Error',
    success: 'Success',
    fill_title_file: 'Enter a title and choose a file',
    fill_all_fields: 'Please fill in all fields',
    invalid_login: 'Invalid email or password',
    backend_server: 'Backend server',
    backend_url: 'Backend URL',
    backend_url_hint: 'For an APK on a phone, use an address reachable from the phone, for example http://192.168.1.10:8080. localhost and 10.0.2.2 do not work on a real phone.',
    invalid_server_url: 'Enter a valid server URL, for example http://192.168.1.10:8080',
    test_connection: 'Test connection',
    server_connection_ok: 'Backend connection works',
    server_connection_failed: 'Backend is not reachable from this device',
    server_saved: 'Backend URL saved',
    saved_material: 'Material was added to the library',
    save_failed: 'Could not save material',
    no_add_rights: 'You do not have permission to add materials.',
    read_in_app: 'Read in app',
    open_document: 'Open document',
    open_source: 'Open official source',
    online: 'Online',
    download_for_reading: 'Download to read',
    unknown_author: 'Unknown author',
    on_server: 'On server',
    read_pages_prefix: 'Read: page',
    of: 'of',
    assigned_discipline: 'Discipline assigned',
    delete_book_title: 'Delete book?',
    delete_book_message: 'will be removed from the library.',
    cancel: 'Cancel',
    download_first: 'Download the book to this device first',
    no_available_file: 'This book has no available file or link yet',
    missing_server_file: 'The book file has not been uploaded to the server yet',
    file_ready: 'The book is downloaded and ready to read',
    download_failed: 'Could not download the book',
    source: 'Source',
    not_specified: 'not specified',
    available_in_app: 'In-app reading is available',
    downloaded_document: 'Document downloaded to this device',
    server_file_hint: 'The file is stored on the server. Download it to read',
    external_link_available: 'External link is available',
    description_missing: 'No description.',
    download_book: 'Download book',
    access_restricted: 'Access restricted',
    read: 'Read',
    no_file: 'No file',
    assign_discipline: 'Assign discipline',
    search_materials: 'Search materials...',
    offline_only: 'Offline only',
    available_online: 'Available online',
    favorite_books: 'Favorites',
    continue_reading: 'Continue reading',
    materials_not_found: 'No materials found',
    reset_filters: 'Reset filters',
    filters: 'Filters',
    sort: 'Sort',
    sort_newest: 'Newest first',
    sort_title: 'By title',
    sort_author: 'By author',
    sort_offline: 'Offline first',
    all_disciplines: 'All disciplines',
    all_categories: 'All categories',
    material_types: 'Material type',
    all_types: 'All types',
    reset: 'Reset',
    apply: 'Apply',
    empty_catalog: 'Catalog is empty',
    no_courses_for_discipline: 'This discipline has no courses yet',
    catalog_access_denied: 'Catalogs are available to administrators and teachers.',
    catalog_subtitle: 'Disciplines, courses and study groups',
    new_discipline: 'New discipline',
    discipline_name: 'Discipline name',
    code_optional: 'Code (optional)',
    name_kk: 'Name in Kazakh',
    name_en: 'Name in English',
    add_course: 'Add course',
    course_name: 'Course name',
    course_year_1_6: 'Course number (1-6)',
    new_group: 'New group',
    group_name: 'Group name',
    group_course: 'Group course',
    admission_year: 'Admission year',
    discipline_not_specified: 'Discipline not specified',
    create_discipline_course_first: 'Create a discipline and course first.',
    add_discipline: 'Add discipline',
    create_first_discipline: 'Create the first discipline, then add courses to it.',
    add_group: 'Add group',
    groups_empty: 'No groups yet. Students will be able to choose a group after one is added.',
    course_year_invalid: 'Course number must be from 1 to 6',
    group_required: 'Enter a group name and choose a course',
    group_add_failed: 'Could not add the group. This name may already exist.',
    discipline_added: 'Discipline added',
    course_added: 'Course added',
    group_added: 'Group added',
    admin_access_denied: 'Access is allowed only for administrators.',
    admin_panel: 'Admin panel',
    admin_subtitle: 'PocketLib users and catalog',
    add_book: 'Add book',
    group_label: 'Group',
    primary_admin: 'Primary admin',
    role_updated: 'User role updated',
    delete_user_title: 'Delete user?',
    specialty: 'Specialty',
    information_systems: 'Information systems',
    registration_date: 'Registration date',
    notifications: 'Notifications',
    appearance: 'Appearance',
    light_theme: 'Light theme',
    dark_theme: 'Dark theme',
    year: 'Year',
    read_online: 'Read online',
    book_search: 'Book search',
    search_books_placeholder: 'Title, author or topic...',
    search_button: 'Search',
    enter_query_hint: 'Enter a query and tap Search',
    nothing_found: 'Nothing found',
    added_to_library: 'added to the library',
    add_book_error: 'Error adding the book',
    open_literature: 'Open literature',
    gutenberg_search_subtitle: 'Search Project Gutenberg classics',
    gutenberg_placeholder: 'Title or author (in English)...',
    find_classics_hint: 'Find world classics for your collection',
    reader_loading: 'Loading book...',
    epub_text_failed: 'Could not convert EPUB to text',
    file_original_hint: 'This file is better opened as the original document',
    download_from_card: 'Download the book from the material card first.',
    prepare_epub_text: 'Preparing EPUB text version...',
    epub_text_open_failed: 'Could not open EPUB text version',
    open_original_failed: 'Could not open the original document. Check that a PDF/EPUB viewer is installed.',
    bookmark_added_section: 'Bookmark added: section',
    bookmark_added_page: 'Bookmark added: page',
    bookmark_removed: 'Bookmark removed',
    section: 'Section',
    page: 'Page',
    original_document: 'Original document',
    bookmarks: 'Bookmarks',
    no_bookmarks: 'No bookmarks yet',
    document: 'Document',
    pdf_original_hint: 'PDF opens as the original file, so images, tables and page layout are preserved.',
    original_format_hint: 'This format is better read as the original document to preserve media and layout.',
    reader_settings: 'Reading settings',
    text_size: 'Text size',
    font: 'Font',
    theme: 'Theme',
    line_spacing: 'Line spacing',
    page_width: 'Page width',
    theme_paper: 'Paper',
    theme_white: 'Light',
    theme_green: 'Calm',
    theme_dark: 'Dark',
    font_serif: 'Book',
    font_sans: 'Modern',
    font_mono: 'Mono',
    font_system: 'System',
    width_narrow: 'Narrow',
    width_medium: 'Medium',
    width_wide: 'Wide',
    line_compact: 'Compact',
    line_normal: 'Normal',
    line_relaxed: 'Relaxed',
    preview_text: 'This is how the book page will look.',
    text_mode: 'Text mode',
    done: 'Done',
  },
} as const;

type TranslationKey = keyof typeof translations.ru;

interface LanguageContextType {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  t: (key: TranslationKey | string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ru',
  setLanguage: () => {},
  t: (key) => translations.ru[key as TranslationKey] || key,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>('ru');

  useEffect(() => {
    AsyncStorage.getItem('app_language').then((stored) => {
      if (stored === 'ru' || stored === 'kk' || stored === 'en') setLanguageState(stored);
    });
  }, []);

  const value = useMemo(() => ({
    language,
    setLanguage: (next: AppLanguage) => {
      setLanguageState(next);
      AsyncStorage.setItem('app_language', next);
    },
    t: (key: TranslationKey | string) => translations[language][key as TranslationKey] || translations.ru[key as TranslationKey] || key,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
