// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: books.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (
    legacy_id,
    title,
    subtitle,
    author,
    year,
    isbn,
    language,
    department,
    department_code,
    publication_type,
    publisher_place,
    publisher_name,
    pages,
    price,
    quantity,
    keywords,
    description,
    library_name,
    location_name,
    html_path,
    raw_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
RETURNING id, legacy_id, title, subtitle, author, year, isbn, language, department, department_code, publication_type, publisher_place, publisher_name, pages, price, quantity, keywords, description, library_name, location_name, html_path, raw_data, created_at, updated_at
`

type CreateBookParams struct {
	LegacyID        pgtype.Int8    `json:"legacy_id"`
	Title           string         `json:"title"`
	Subtitle        pgtype.Text    `json:"subtitle"`
	Author          pgtype.Text    `json:"author"`
	Year            pgtype.Int4    `json:"year"`
	Isbn            pgtype.Text    `json:"isbn"`
	Language        pgtype.Text    `json:"language"`
	Department      pgtype.Text    `json:"department"`
	DepartmentCode  pgtype.Text    `json:"department_code"`
	PublicationType pgtype.Text    `json:"publication_type"`
	PublisherPlace  pgtype.Text    `json:"publisher_place"`
	PublisherName   pgtype.Text    `json:"publisher_name"`
	Pages           pgtype.Int4    `json:"pages"`
	Price           pgtype.Numeric `json:"price"`
	Quantity        pgtype.Int4    `json:"quantity"`
	Keywords        pgtype.Text    `json:"keywords"`
	Description     pgtype.Text    `json:"description"`
	LibraryName     pgtype.Text    `json:"library_name"`
	LocationName    pgtype.Text    `json:"location_name"`
	HtmlPath        pgtype.Text    `json:"html_path"`
	RawData         []byte         `json:"raw_data"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.LegacyID,
		arg.Title,
		arg.Subtitle,
		arg.Author,
		arg.Year,
		arg.Isbn,
		arg.Language,
		arg.Department,
		arg.DepartmentCode,
		arg.PublicationType,
		arg.PublisherPlace,
		arg.PublisherName,
		arg.Pages,
		arg.Price,
		arg.Quantity,
		arg.Keywords,
		arg.Description,
		arg.LibraryName,
		arg.LocationName,
		arg.HtmlPath,
		arg.RawData,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LegacyID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Year,
		&i.Isbn,
		&i.Language,
		&i.Department,
		&i.DepartmentCode,
		&i.PublicationType,
		&i.PublisherPlace,
		&i.PublisherName,
		&i.Pages,
		&i.Price,
		&i.Quantity,
		&i.Keywords,
		&i.Description,
		&i.LibraryName,
		&i.LocationName,
		&i.HtmlPath,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBookFile = `-- name: CreateBookFile :one
INSERT INTO book_files (
    book_id,
    bucket,
    object_key,
    file_name,
    content_type,
    size_bytes,
    etag
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, book_id, bucket, object_key, file_name, content_type, size_bytes, etag, created_at
`

type CreateBookFileParams struct {
	BookID      pgtype.UUID `json:"book_id"`
	Bucket      string      `json:"bucket"`
	ObjectKey   string      `json:"object_key"`
	FileName    string      `json:"file_name"`
	ContentType pgtype.Text `json:"content_type"`
	SizeBytes   pgtype.Int8 `json:"size_bytes"`
	Etag        pgtype.Text `json:"etag"`
}

func (q *Queries) CreateBookFile(ctx context.Context, arg CreateBookFileParams) (BookFile, error) {
	row := q.db.QueryRow(ctx, createBookFile,
		arg.BookID,
		arg.Bucket,
		arg.ObjectKey,
		arg.FileName,
		arg.ContentType,
		arg.SizeBytes,
		arg.Etag,
	)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Bucket,
		&i.ObjectKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const createS3Import = `-- name: CreateS3Import :one
INSERT INTO s3_imports (
    bucket,
    object_key,
    source_kind,
    status,
    etag,
    size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, bucket, object_key, source_kind, status, etag, size_bytes, books_imported, error_message, created_at, finished_at
`

type CreateS3ImportParams struct {
	Bucket     string         `json:"bucket"`
	ObjectKey  string         `json:"object_key"`
	SourceKind S3SourceKind   `json:"source_kind"`
	Status     S3ImportStatus `json:"status"`
	Etag       pgtype.Text    `json:"etag"`
	SizeBytes  pgtype.Int8    `json:"size_bytes"`
}

func (q *Queries) CreateS3Import(ctx context.Context, arg CreateS3ImportParams) (S3Import, error) {
	row := q.db.QueryRow(ctx, createS3Import,
		arg.Bucket,
		arg.ObjectKey,
		arg.SourceKind,
		arg.Status,
		arg.Etag,
		arg.SizeBytes,
	)
	var i S3Import
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.SourceKind,
		&i.Status,
		&i.Etag,
		&i.SizeBytes,
		&i.BooksImported,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishS3Import = `-- name: FinishS3Import :one
UPDATE s3_imports
SET
    status = $2,
    books_imported = $3,
    error_message = $4,
    finished_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, bucket, object_key, source_kind, status, etag, size_bytes, books_imported, error_message, created_at, finished_at
`

type FinishS3ImportParams struct {
	ID            pgtype.UUID    `json:"id"`
	Status        S3ImportStatus `json:"status"`
	BooksImported int32          `json:"books_imported"`
	ErrorMessage  pgtype.Text    `json:"error_message"`
}

func (q *Queries) FinishS3Import(ctx context.Context, arg FinishS3ImportParams) (S3Import, error) {
	row := q.db.QueryRow(ctx, finishS3Import,
		arg.ID,
		arg.Status,
		arg.BooksImported,
		arg.ErrorMessage,
	)
	var i S3Import
	err := row.Scan(
		&i.ID,
		&i.Bucket,
		&i.ObjectKey,
		&i.SourceKind,
		&i.Status,
		&i.Etag,
		&i.SizeBytes,
		&i.BooksImported,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getBook = `-- name: GetBook :one
SELECT id, legacy_id, title, subtitle, author, year, isbn, language, department, department_code, publication_type, publisher_place, publisher_name, pages, price, quantity, keywords, description, library_name, location_name, html_path, raw_data, created_at, updated_at
FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id pgtype.UUID) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LegacyID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Year,
		&i.Isbn,
		&i.Language,
		&i.Department,
		&i.DepartmentCode,
		&i.PublicationType,
		&i.PublisherPlace,
		&i.PublisherName,
		&i.Pages,
		&i.Price,
		&i.Quantity,
		&i.Keywords,
		&i.Description,
		&i.LibraryName,
		&i.LocationName,
		&i.HtmlPath,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestBookFile = `-- name: GetLatestBookFile :one
SELECT id, book_id, bucket, object_key, file_name, content_type, size_bytes, etag, created_at
FROM book_files
WHERE book_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestBookFile(ctx context.Context, bookID pgtype.UUID) (BookFile, error) {
	row := q.db.QueryRow(ctx, getLatestBookFile, bookID)
	var i BookFile
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Bucket,
		&i.ObjectKey,
		&i.FileName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Etag,
		&i.CreatedAt,
	)
	return i, err
}

const listBookFiles = `-- name: ListBookFiles :many
SELECT id, book_id, bucket, object_key, file_name, content_type, size_bytes, etag, created_at
FROM book_files
WHERE book_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListBookFiles(ctx context.Context, bookID pgtype.UUID) ([]BookFile, error) {
	rows, err := q.db.Query(ctx, listBookFiles, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BookFile{}
	for rows.Next() {
		var i BookFile
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Bucket,
			&i.ObjectKey,
			&i.FileName,
			&i.ContentType,
			&i.SizeBytes,
			&i.Etag,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBooks = `-- name: ListBooks :many
SELECT id, legacy_id, title, subtitle, author, year, isbn, language, department, department_code, publication_type, publisher_place, publisher_name, pages, price, quantity, keywords, description, library_name, location_name, html_path, raw_data, created_at, updated_at
FROM books
WHERE
    (
        $3::TEXT IS NULL OR
        title ILIKE '%' || $3::TEXT || '%' OR
        author ILIKE '%' || $3::TEXT || '%' OR
        isbn ILIKE '%' || $3::TEXT || '%'
    )
ORDER BY created_at DESC, id DESC
LIMIT $1 OFFSET $2
`

type ListBooksParams struct {
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
	Query  pgtype.Text `json:"query"`
}

func (q *Queries) ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks, arg.Limit, arg.Offset, arg.Query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Book{}
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.LegacyID,
			&i.Title,
			&i.Subtitle,
			&i.Author,
			&i.Year,
			&i.Isbn,
			&i.Language,
			&i.Department,
			&i.DepartmentCode,
			&i.PublicationType,
			&i.PublisherPlace,
			&i.PublisherName,
			&i.Pages,
			&i.Price,
			&i.Quantity,
			&i.Keywords,
			&i.Description,
			&i.LibraryName,
			&i.LocationName,
			&i.HtmlPath,
			&i.RawData,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBookByLegacyID = `-- name: UpsertBookByLegacyID :one
INSERT INTO books (
    legacy_id,
    title,
    subtitle,
    author,
    year,
    isbn,
    language,
    department,
    department_code,
    publication_type,
    publisher_place,
    publisher_name,
    pages,
    price,
    quantity,
    keywords,
    description,
    library_name,
    location_name,
    html_path,
    raw_data
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15, $16, $17, $18, $19, $20, $21
)
ON CONFLICT (legacy_id) DO UPDATE SET
    title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    author = EXCLUDED.author,
    year = EXCLUDED.year,
    isbn = EXCLUDED.isbn,
    language = EXCLUDED.language,
    department = EXCLUDED.department,
    department_code = EXCLUDED.department_code,
    publication_type = EXCLUDED.publication_type,
    publisher_place = EXCLUDED.publisher_place,
    publisher_name = EXCLUDED.publisher_name,
    pages = EXCLUDED.pages,
    price = EXCLUDED.price,
    quantity = EXCLUDED.quantity,
    keywords = EXCLUDED.keywords,
    description = EXCLUDED.description,
    library_name = EXCLUDED.library_name,
    location_name = EXCLUDED.location_name,
    html_path = EXCLUDED.html_path,
    raw_data = EXCLUDED.raw_data,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, legacy_id, title, subtitle, author, year, isbn, language, department, department_code, publication_type, publisher_place, publisher_name, pages, price, quantity, keywords, description, library_name, location_name, html_path, raw_data, created_at, updated_at
`

type UpsertBookByLegacyIDParams struct {
	LegacyID        pgtype.Int8    `json:"legacy_id"`
	Title           string         `json:"title"`
	Subtitle        pgtype.Text    `json:"subtitle"`
	Author          pgtype.Text    `json:"author"`
	Year            pgtype.Int4    `json:"year"`
	Isbn            pgtype.Text    `json:"isbn"`
	Language        pgtype.Text    `json:"language"`
	Department      pgtype.Text    `json:"department"`
	DepartmentCode  pgtype.Text    `json:"department_code"`
	PublicationType pgtype.Text    `json:"publication_type"`
	PublisherPlace  pgtype.Text    `json:"publisher_place"`
	PublisherName   pgtype.Text    `json:"publisher_name"`
	Pages           pgtype.Int4    `json:"pages"`
	Price           pgtype.Numeric `json:"price"`
	Quantity        pgtype.Int4    `json:"quantity"`
	Keywords        pgtype.Text    `json:"keywords"`
	Description     pgtype.Text    `json:"description"`
	LibraryName     pgtype.Text    `json:"library_name"`
	LocationName    pgtype.Text    `json:"location_name"`
	HtmlPath        pgtype.Text    `json:"html_path"`
	RawData         []byte         `json:"raw_data"`
}

func (q *Queries) UpsertBookByLegacyID(ctx context.Context, arg UpsertBookByLegacyIDParams) (Book, error) {
	row := q.db.QueryRow(ctx, upsertBookByLegacyID,
		arg.LegacyID,
		arg.Title,
		arg.Subtitle,
		arg.Author,
		arg.Year,
		arg.Isbn,
		arg.Language,
		arg.Department,
		arg.DepartmentCode,
		arg.PublicationType,
		arg.PublisherPlace,
		arg.PublisherName,
		arg.Pages,
		arg.Price,
		arg.Quantity,
		arg.Keywords,
		arg.Description,
		arg.LibraryName,
		arg.LocationName,
		arg.HtmlPath,
		arg.RawData,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.LegacyID,
		&i.Title,
		&i.Subtitle,
		&i.Author,
		&i.Year,
		&i.Isbn,
		&i.Language,
		&i.Department,
		&i.DepartmentCode,
		&i.PublicationType,
		&i.PublisherPlace,
		&i.PublisherName,
		&i.Pages,
		&i.Price,
		&i.Quantity,
		&i.Keywords,
		&i.Description,
		&i.LibraryName,
		&i.LocationName,
		&i.HtmlPath,
		&i.RawData,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
