// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type S3ImportStatus string

const (
	S3ImportStatusPENDING S3ImportStatus = "PENDING"
	S3ImportStatusDONE    S3ImportStatus = "DONE"
	S3ImportStatusFAILED  S3ImportStatus = "FAILED"
)

func (e *S3ImportStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = S3ImportStatus(s)
	case string:
		*e = S3ImportStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for S3ImportStatus: %T", src)
	}
	return nil
}

type NullS3ImportStatus struct {
	S3ImportStatus S3ImportStatus `json:"s3_import_status"`
	Valid          bool           `json:"valid"` // Valid is true if S3ImportStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullS3ImportStatus) Scan(value interface{}) error {
	if value == nil {
		ns.S3ImportStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.S3ImportStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullS3ImportStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.S3ImportStatus), nil
}

type S3SourceKind string

const (
	S3SourceKindBOOKSXML    S3SourceKind = "BOOKS_XML"
	S3SourceKindREGISTRYXML S3SourceKind = "REGISTRY_XML"
	S3SourceKindBOOKFILE    S3SourceKind = "BOOK_FILE"
)

func (e *S3SourceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = S3SourceKind(s)
	case string:
		*e = S3SourceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for S3SourceKind: %T", src)
	}
	return nil
}

type NullS3SourceKind struct {
	S3SourceKind S3SourceKind `json:"s3_source_kind"`
	Valid        bool         `json:"valid"` // Valid is true if S3SourceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullS3SourceKind) Scan(value interface{}) error {
	if value == nil {
		ns.S3SourceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.S3SourceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullS3SourceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.S3SourceKind), nil
}

type Book struct {
	ID              pgtype.UUID        `json:"id"`
	LegacyID        pgtype.Int8        `json:"legacy_id"`
	Title           string             `json:"title"`
	Subtitle        pgtype.Text        `json:"subtitle"`
	Author          pgtype.Text        `json:"author"`
	Year            pgtype.Int4        `json:"year"`
	Isbn            pgtype.Text        `json:"isbn"`
	Language        pgtype.Text        `json:"language"`
	Department      pgtype.Text        `json:"department"`
	DepartmentCode  pgtype.Text        `json:"department_code"`
	PublicationType pgtype.Text        `json:"publication_type"`
	PublisherPlace  pgtype.Text        `json:"publisher_place"`
	PublisherName   pgtype.Text        `json:"publisher_name"`
	Pages           pgtype.Int4        `json:"pages"`
	Price           pgtype.Numeric     `json:"price"`
	Quantity        pgtype.Int4        `json:"quantity"`
	Keywords        pgtype.Text        `json:"keywords"`
	Description     pgtype.Text        `json:"description"`
	LibraryName     pgtype.Text        `json:"library_name"`
	LocationName    pgtype.Text        `json:"location_name"`
	HtmlPath        pgtype.Text        `json:"html_path"`
	RawData         []byte             `json:"raw_data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type BookFile struct {
	ID          pgtype.UUID        `json:"id"`
	BookID      pgtype.UUID        `json:"book_id"`
	Bucket      string             `json:"bucket"`
	ObjectKey   string             `json:"object_key"`
	FileName    string             `json:"file_name"`
	ContentType pgtype.Text        `json:"content_type"`
	SizeBytes   pgtype.Int8        `json:"size_bytes"`
	Etag        pgtype.Text        `json:"etag"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BookRegistryReceipt struct {
	ID          pgtype.UUID        `json:"id"`
	LegacyID    int64              `json:"legacy_id"`
	Number      string             `json:"number"`
	ReceiptDate pgtype.Date        `json:"receipt_date"`
	Quantity    int32              `json:"quantity"`
	Amount      pgtype.Numeric     `json:"amount"`
	SourceName  pgtype.Text        `json:"source_name"`
	RawData     []byte             `json:"raw_data"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type S3Import struct {
	ID            pgtype.UUID        `json:"id"`
	Bucket        string             `json:"bucket"`
	ObjectKey     string             `json:"object_key"`
	SourceKind    S3SourceKind       `json:"source_kind"`
	Status        S3ImportStatus     `json:"status"`
	Etag          pgtype.Text        `json:"etag"`
	SizeBytes     pgtype.Int8        `json:"size_bytes"`
	BooksImported int32              `json:"books_imported"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	FinishedAt    pgtype.Timestamptz `json:"finished_at"`
}
