// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateBookFile(ctx context.Context, arg CreateBookFileParams) (BookFile, error)
	CreateS3Import(ctx context.Context, arg CreateS3ImportParams) (S3Import, error)
	FinishS3Import(ctx context.Context, arg FinishS3ImportParams) (S3Import, error)
	GetBook(ctx context.Context, id pgtype.UUID) (Book, error)
	GetLatestBookFile(ctx context.Context, bookID pgtype.UUID) (BookFile, error)
	ListBookFiles(ctx context.Context, bookID pgtype.UUID) ([]BookFile, error)
	ListBooks(ctx context.Context, arg ListBooksParams) ([]Book, error)
	UpsertBookByLegacyID(ctx context.Context, arg UpsertBookByLegacyIDParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
